import type { Job, JobEvent, ManifestRow } from './types'

const now = Date.now()

export const jobs: Job[] = [
  {
    id: 'job-analyze-20260307-01',
    kind: 'analyze',
    status: 'succeeded',
    phase: 'manifest_written',
    progress: 100,
    started_at: new Date(now - 1000 * 60 * 18).toISOString(),
    finished_at: new Date(now - 1000 * 60 * 9).toISOString(),
    manifest_path: '~/.fileman/workspaces/default/.fileman/manifests/manifest-job-analyze-20260307-01.jsonl',
    report_path: '~/.fileman/workspaces/default/.fileman/artifacts/report/report-job-analyze-20260307-01.json',
    dry_run_verified: true,
    strict_integrity_ready: true,
    summary: {
      total: 124,
      with_error: 4,
      by_media_type: { image: 93, audio: 12, pdf: 19 },
      by_category: { 工作: 42, 旅行: 15, 产品: 22, 文档: 32, 其他: 13 },
      by_status: { pending: 120, error: 4 },
      error_codes: { AI_TIMEOUT: 2, DOC_CONVERT_FAIL: 1, AUDIO_PREP_FAIL: 1 },
    },
  },
  {
    id: 'job-apply-20260307-03',
    kind: 'apply',
    status: 'running',
    phase: 'dry_run_validation',
    progress: 58,
    started_at: new Date(now - 1000 * 60 * 4).toISOString(),
    manifest_path: '~/.fileman/workspaces/default/.fileman/manifests/manifest-job-analyze-20260307-01.jsonl',
    dry_run_verified: false,
    strict_integrity_ready: true,
    latest_error: 'Detected 2 path collisions in dry-run preflight.',
  },
  {
    id: 'job-rollback-20260307-05',
    kind: 'rollback',
    status: 'queued',
    phase: 'awaiting_confirmation',
    progress: 0,
    started_at: new Date(now - 1000 * 60).toISOString(),
    manifest_path: '~/.fileman/workspaces/default/.fileman/manifests/manifest-job-analyze-20260307-00.jsonl',
    dry_run_verified: true,
    strict_integrity_ready: false,
    latest_error: 'Missing rollback_sig on 3 rows.',
  },
]

export const eventsByJobId: Record<string, JobEvent[]> = {
  'job-analyze-20260307-01': [
    {
      id: 'evt-1',
      timestamp: new Date(now - 1000 * 60 * 17).toISOString(),
      level: 'INFO',
      message: 'Scan started: 124 files discovered.',
    },
    {
      id: 'evt-2',
      timestamp: new Date(now - 1000 * 60 * 14).toISOString(),
      level: 'INFO',
      message: 'Gemini classification completed for 117 files.',
    },
    {
      id: 'evt-3',
      timestamp: new Date(now - 1000 * 60 * 12).toISOString(),
      level: 'WARN',
      message: '4 rows contain recoverable errors. Check manifest before apply.',
    },
  ],
  'job-apply-20260307-03': [
    {
      id: 'evt-4',
      timestamp: new Date(now - 1000 * 60 * 3).toISOString(),
      level: 'INFO',
      message: 'Dry-run started with --verify-sha1 and --resume.',
    },
    {
      id: 'evt-5',
      timestamp: new Date(now - 1000 * 60 * 2).toISOString(),
      level: 'ERROR',
      message: '2 destination conflicts found. Awaiting manual confirmation.',
    },
  ],
}

export const manifestRows: ManifestRow[] = [
  {
    id: 'row-1',
    file_name: 'IMG_3021.jpg',
    media_type: 'image',
    category: '旅行',
    title: '西雅图海边晚霞',
    tags: ['travel', 'sunset'],
    status: 'pending',
    error_code: '',
    target_path: '~/.fileman/workspaces/default/data/organized/旅行/西雅图海边晚霞__d1f78a22.jpg',
    target_suggestion: '~/.fileman/workspaces/default/data/organized/旅行/西雅图海边晚霞__d1f78a22.jpg',
    confidence: 0.91,
    original_path: '~/.fileman/workspaces/default/data/raw/IMG_3021.jpg',
    notes: 'Skyline + sunset with strong confidence.',
    ignore: false,
    metadata: {
      width: '4032',
      height: '3024',
      mime: 'image/jpeg',
      exif_datetime: '2026-02-28T18:41:02',
    },
  },
  {
    id: 'row-2',
    file_name: 'voice-note-11.m4a',
    media_type: 'audio',
    category: '工作',
    title: '产品站会录音',
    tags: ['voice', 'meeting'],
    status: 'error',
    error_code: 'AUDIO_PREP_FAIL',
    target_path: '',
    target_suggestion: '~/.fileman/workspaces/default/data/organized/工作/产品站会录音__a45b9912.m4a',
    confidence: 0.77,
    original_path: '~/.fileman/workspaces/default/data/raw/voice-note-11.m4a',
    notes: 'ffmpeg parse failed, retry suggested.',
    ignore: false,
    metadata: {
      duration_s: '121.4',
      sample_rate: '44100',
      channels: '2',
    },
  },
  {
    id: 'row-3',
    file_name: 'invoice-2026-03.pdf',
    media_type: 'pdf',
    category: '文档',
    title: '三月供应商发票',
    tags: ['invoice', 'finance'],
    status: 'pending',
    error_code: '',
    target_path: '~/.fileman/workspaces/default/data/organized/文档/三月供应商发票__1f9e9321.pdf',
    target_suggestion: '~/.fileman/workspaces/default/data/organized/文档/三月供应商发票__1f9e9321.pdf',
    confidence: 0.88,
    original_path: '~/.fileman/workspaces/default/data/raw/invoice-2026-03.pdf',
    notes: 'High confidence extraction, includes amount fields.',
    ignore: false,
    metadata: {
      pages: '4',
      mime: 'application/pdf',
      file_mtime: '2026-03-06T11:09:45',
    },
  },
  {
    id: 'row-4',
    file_name: 'IMG_3019.jpg',
    media_type: 'image',
    category: '旅行',
    title: '西雅图海边晚霞',
    tags: ['travel', 'duplicate'],
    status: 'duplicate',
    error_code: '',
    target_path: '~/.fileman/workspaces/default/data/organized/旅行/西雅图海边晚霞__d1f78a22.jpg',
    target_suggestion: '~/.fileman/workspaces/default/data/organized/旅行/西雅图海边晚霞__d1f78a22_2.jpg',
    dedupe_of: 'row-1',
    confidence: 0.9,
    original_path: '~/.fileman/workspaces/default/data/raw/IMG_3019.jpg',
    notes: 'Detected as duplicate of IMG_3021.jpg by hash.',
    ignore: false,
    metadata: {
      width: '4032',
      height: '3024',
      mime: 'image/jpeg',
      sha1: 'd1f78a22...',
    },
  },
]
