name: scorecards

on:
  branch_protection_rule:
  schedule:
    - cron: "45 3 * * 1"
  workflow_dispatch:

permissions:
  actions: read
  contents: read

concurrency:
  group: scorecards-${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name != 'workflow_dispatch' }}

jobs:
  analysis:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
          clean: true
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true
      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: scorecard-results
          path: results.sarif
          if-no-files-found: error
          overwrite: true
      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc
        with:
          sarif_file: results.sarif
